basePath: /api/v1
definitions:
  controller.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  controller.TokenResponse:
    properties:
      token:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: integer
      password:
        type: string
      roleID:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  description: Describe your API here
  title: Your Project's Name
  version: "1.0"
paths:
  /generate-token:
    post:
      consumes:
      - application/json
      description: Generate JWT token with the provided userID
      parameters:
      - description: User ID
        in: body
        name: userID
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.TokenResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Generate JWT token
      tags:
      - Authentication
  /login:
    post:
      consumes:
      - application/json
      description: Log in as an existing user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: User login
      tags:
      - Users
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: user created successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Register new user
      tags:
      - Users
swagger: "2.0"
